version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: catracleDB
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  web:
    container_name: catracleApp
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - mongo
    volumes:
      - .:/usr/src/app
